packages:
  - "."
  - "packages/configs/tsconfig"
  - "packages/configs/prettier-config"
  - "packages/configs/eslint-config"
  - "packages/configs/stylelint-config"
  - "packages/turndown"
  - "packages/schema"
  - "packages/hot"