packages:
  - "."
  - "docs"
  - "packages/configs/*"
  - "packages/utils"
  - "packages/hot"
  - "packages/ansi"
  - "packages/turndown"
  - "packages/schema"
  - "packages/uws"
  - "examples/using-paths"
  - "examples/using-tailwind"
 # - "examples/*"
  - "straps/test"