name: merge

on:
  push:
    branches: [ master ]

  workflow_dispatch:

concurrency: prr:deploy

jobs:
  merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpx pr-release merge --target master --source next --commit --force --clean --changelog --compact
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    # The following will publish the release to npm
#    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
#      name: Setup NPM Auth
#      env:
#        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#    - run: npm publish
#      name: Publish








