name: pr

on:
  push:
    branches: [ next ]

  workflow_dispatch:

concurrency: prr:pre-release

jobs:
  pr:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpx pr-release pr --verbose --target master --source next --compact --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    # The following will publish a prerelease to npm
#    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
#      name: Setup NPM Auth
#      env:
#        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#    - run: npx pr-release infer-prerelease --preid=next --verbose --publish
#      name: Publish
